name: gwt_mail_sample
description: A Dart app that uses AngularDart
environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: 5.0.0-alpha+4
  angular_components: 0.9.0-alpha+3

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

web:
  compiler:
    debug: dartdevc

dependency_overrides:
  # Required to use AngularDart bleeding edge.
  analyzer: ^0.31.0-alpha

transformers:
- angular
- dart_to_js_script_rewriter
- $dart2js:
    commandLineOptions:
      - --trust-type-annotations
      - --trust-primitives
      - --dump-info
